image: Visual Studio 2017

install:
  - ps: Set-Culture de-DE

build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

test_script:
  - ctest -C Debug

on_finish:
  - appveyor PushArtifact tst_database-junit.xml
  - appveyor PushArtifact tst_integration-junit.xml
  - appveyor PushArtifact tst_tokenizer-junit.xml

artifacts:
  - path: 'build\Debug\*tt1*.exe'
    name: executables
  - path: 'build\*-junit.xml'
    name: test results