image: Visual Studio 2017

build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest -C Debug

after_build:
  - $wc = New-Object 'System.Net.WebClient'
  - $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\xunit-results.xml))

artifacts:
  - path: 'build\Debug\*tt1*.exe'
    name: executables