image: Visual Studio 2017

build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

test_script:
  - ctest -C Debug

artifacts:
  - path: 'build\Debug\*tt1*.exe'
    name: executables