image: Visual Studio 2017

build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .

test_script:
  - ctest -C Debug

on_finish:
  - appveyor PushArtifact Debug\tst_database-junit.xml
  - appveyor PushArtifact Debug\tst_integration-junit.xml
  - appveyor PushArtifact Debug\tst_tokenizer-junit.xml
  - appveyor AddTest database -Framework xUnit -FileName Debug\tst_database-junit.xml
  - appveyor AddTest integration -Framework xUnit -FileName Debug\tst_integration-junit.xml
  - appveyor AddTest tokenizer -Framework xUnit -FileName Debug\tst_tokenizer-junit.xml

artifacts:
  - path: 'build\Debug\*tt1*.exe'
    name: executables
  - path: 'build\*-junit.xml'
    name: test results