language: cpp
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - lcov

install:
  # taken from https://github.com/Microsoft/GSL/blob/9d65e74400976b3509833f49b16d401600c7317d/.travis.yml#L189
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p "${DEPS_DIR}"
  - cd "${DEPS_DIR}"
  ############################################################################
  # Install a recent CMake (unless already installed on OS X)
  ############################################################################
  - CMAKE_VERSION=3.9.0
  - |
    CMAKE_URL="https://cmake.org/files/v${CMAKE_VERSION%.[0-9]}/cmake-${CMAKE_VERSION}-Linux-x86_64.tar.gz"
    mkdir cmake && travis_retry wget --no-check-certificate -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
    export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cmake --version
  - ctest --version

  ############################################################################
  # GCC version
  ############################################################################
  - export CXX=g++-7
  - $CXX --version

before_script:
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest

after_success:
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --remove coverage.info '**/3rdparty/*' --output-file coverage.info # filter out 3rd party
  - lcov --list coverage.info # debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) -X gcov || echo "Codecov did not collect coverage reports"